{
# 公众号配置
# 公众号appId
"app_id": "wxb7fdf54075e60461",
# 公众号appSecret
"app_secret": "64bcc5eadcb90982be0126ecf001f3e4",
# 模板消息id
"template_id": "-sn0pNs_-zy1p80tgxZwQPlNQKw3XqI3ix4mRCPTxSI",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["oHdgf5oKdLOuVGBcxBY5mb2VQSSk"],

# 信息配置
# 和风天气apikey
"weather_key": "65d7ce7b7f134a4cb317d4ae79118cbc",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦
"region": "河北省，邯郸市",
# 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"name": "何女士", "birthday": "r2000-09-24"},
# 生日2
"birthday2": {"name": "何女士", "birthday": "r2000-09-24"},
# 在一起的日子，格式同上，暂不不支持农历
"love_date": "2022-10-1",
# 金句中文，如果设置了，则会显示这里的，如果为空，默认会读取金山的每日金句
"note_ch": "相逢的意义在于照亮彼此，很开心我们能出现在彼此的生命里，成为彼此最重要的人",
# 金句英文
"note_en": "I love you, not on impulse, but through deliberation, perseverance. and full of love. I just want to give it to you. Don't underestimate my
determination to go with you. l will be serious, grand, and give you all my love and exceptions. I am sincere!"
}
